### PR TITLE
Fix a bug around nvim refactoring (and clean up changetracker code)

### LINKED ISSUE #213: nvim: Refactoring (renaming) into multiple files crashes when some aren't open yet
We saw this when renaming/refactoring with rust-analyzer into files that weren't already open.
A rope error (conflict between buffer and crdt) will happen on writing/saving the files.

We see "open" messages for the newly-opened files, but the edits Vim does to them are probably not communicated.

### PR DESCRIPTION
**Pull request by blinry**
This fixes #213.

### CODE REVIEW

File: nvim-plugin/lua/ethersync/changetracker.lua [hunk 1]
```diff
@@ -23,20 +24,194 @@ function M.get_all_lines_respecting_eol(buffer)
...
+    local function line_change(first_line, last_line, new_last_line)
+        -- TODO: optimize with a cache
+        local curr_lines = M.get_all_lines_respecting_eol(buffer)
+
+        local prev_lines = prev_lines_global
+        prev_lines_global = curr_lines
+
+        -- Are we currently ignoring edits? If so, do nothing.
+        if ignore_edits then
+            prev_lines_global = curr_lines
```
Comment (zormit) [inline nvim-plugin/lua/ethersync/changetracker.lua]:
```suggestion
```
this has been set in line 183 already

File: nvim-plugin/lua/ethersync/changetracker.lua [hunk 2]
```diff
@@ -23,20 +24,194 @@ function M.get_all_lines_respecting_eol(buffer)
...
+
 -- Subscribes the callback to changes for a given buffer id and reports with a delta.
 --
 -- The delta can be expected to be in the format as specified in the daemon-editor protocol.
-function M.track_changes(buffer, callback)
+function M.track_changes(buffer, initial_lines, callback)
     -- Used to remember the previous content of the buffer, so that we can
     -- calculate the difference between the previous and the current content.
-    local prev_lines = M.get_all_lines_respecting_eol(buffer)
+    local prev_lines_global = initial_lines
```
Comment (zormit) [inline nvim-plugin/lua/ethersync/changetracker.lua]: i find the name of `prev_lines_global` as a local variable slightly confusing :D TODO: better name?

**Review by zormit — APPROVED** [review]
